// Code generated by mockery v1.0.0. DO NOT EDIT.

package cloud

import api "github.com/containership/csctl/cloud/api"
import auth "github.com/containership/csctl/cloud/auth"

import mock "github.com/stretchr/testify/mock"
import provision "github.com/containership/csctl/cloud/provision"

// Interface is an autogenerated mock type for the Interface type
type Interface struct {
	mock.Mock
}

// API provides a mock function with given fields:
func (_m *Interface) API() api.Interface {
	ret := _m.Called()

	var r0 api.Interface
	if rf, ok := ret.Get(0).(func() api.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.Interface)
		}
	}

	return r0
}

// Auth provides a mock function with given fields:
func (_m *Interface) Auth() auth.Interface {
	ret := _m.Called()

	var r0 auth.Interface
	if rf, ok := ret.Get(0).(func() auth.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.Interface)
		}
	}

	return r0
}

// Provision provides a mock function with given fields:
func (_m *Interface) Provision() provision.Interface {
	ret := _m.Called()

	var r0 provision.Interface
	if rf, ok := ret.Get(0).(func() provision.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(provision.Interface)
		}
	}

	return r0
}
